mermaid: [
    `%%{init: {'theme':'base','themeVariables':{'fontSize':'18px'}}}%%\nflowchart TD\n\nTITLE[\"📖 GRAPH-1:<br/>(ଉପହାର ଓ ତାହାର ମୂଲ୍ୟ)<br/>Lead In — Gifts and Their Value\"]\n\nTITLE --> INTRO\n\nsubgraph INTRO[ ]\ndirection LR\nA[\"🟡 (ଆଲୋଚନା) Discussion\"]\nA --> I1[\"(ଜନ୍ମଦିନ, ବିବାହ କିମ୍ବା ବିଶେଷ ଅବସରରେ<br/>ଉପହାର ଦିଆଯାଏ।)<br/>Gifts given on birthdays,<br/>weddings or special days.\"]\nA --> I2[\"(ସାଥୀମାନେ କେଉଁ ଉପହାର ଦେବେ<br/>ତାହା ଆଲୋଚନା କରନ୍ତି।)<br/>Classmates discuss<br/>what gifts they'd give.\"]\nA --> I3[\"(ଛୋଟ ଉପହାର କାହିଁକି ଏତେ<br/>ମୂଲ୍ୟବାନ ହୋଇଯାଏ?)<br/>Why does a small gift<br/>become so valuable?\"]\nend\n\nINTRO --> MAIN\n\nsubgraph MAIN[ ]\ndirection LR\nM[\"🟢 (ପ୍ରାଇସଲେସ ର ଅର୍ଥ) Meaning of 'Priceless'\"]\nM --> M1[\"(ପ୍ରାଇସଲେସ ଅର୍ଥ ଉଚ୍ଚ ମୂଲ୍ୟ<br/>ଥିବା ବସ୍ତୁ।)<br/>Priceless means<br/>something of high value.\"]\nM --> M2[\"(ଏହା ବିରଳ ହେତୁ<br/>ମୂଲ୍ୟବାନ ଅଟେ।)<br/>It is valuable<br/>because it is rare.\"]\nM --> M3[\"(କାହାଣୀଟି ଏକ ରେଷ୍ଟୁରାଣ୍ଟରେ<br/>ଆରମ୍ଭ ହୁଏ।)<br/>The story is set<br/>in a restaurant.\"]\nend\n\nMAIN --> CONCLUSION\n\nsubgraph CONCLUSION[ ]\ndirection LR\nC[\"🔵 (ଉଦ୍ଦେଶ୍ୟ) Purpose\"]\nC --> C1[\"(ପାଠକମାନେ ନିଜ ଆଲୋଚନା ବିନ୍ଦୁକୁ<br/>କାହାଣୀ ସହିତ ମେଳ କରିବେ।)<br/>Readers must match their<br/>discussion points to the story.\"]\nC --> C2[\"(କାହାଣୀ କାହିଁକି ଏକ ଉପହାର<br/>ଅମୂଲ୍ୟ ହୋଇପାରେ ତାହା ଦେଖାଏ।)<br/>The story reveals why a<br/>gift can be priceless.\"]\nC --> C3[\"(ଶୀର୍ଷକ: 'The Priceless Gift'।)<br/>Title: 'The Priceless Gift'.\"]\nend\n\nlinkStyle 0 stroke-width:0px;\nlinkStyle 4 stroke-width:0px;\nlinkStyle 8 stroke-width:0px;\n\nclassDef title fill:#FFE082,stroke:#FF6F00,stroke-width:3px,color:#000,font-weight:bold;\nclassDef intro fill:#BBDEFB,stroke:#1E88E5,stroke-width:2px,font-weight:bold;\nclassDef body fill:#C8E6C9,stroke:#2E7D32,stroke-width:2px,font-weight:bold;\nclassDef conclusion fill:#F8BBD0,stroke:#C2185B,stroke-width:2px,font-weight:bold;\n\nclass TITLE title;\nclass A,I1,I2,I3 intro;\nclass M,M1,M2,M3 body;\nclass C,C1,C2,C3 conclusion;`,

    `%%{init: {'theme':'base','themeVariables':{'fontSize':'18px'}}}%%\nflowchart TD\n\nTITLE[\"📖 GRAPH-2:<br/>(ଭାଗ-I — ଭିଡ଼ପୂର୍ଣ୍ଣ ରେଷ୍ଟୁରାଣ୍ଟ)<br/>Part I — The Crowded Restaurant\"]\n\nTITLE --> INTRO\n\nsubgraph INTRO[ ]\ndirection LR\nA[\"🟡 (ପରିବେଶ) The Setting\"]\nA --> I1[\"(ଲେଖକ ଏକ ନିରାମିଷ ରେଷ୍ଟୁରାଣ୍ଟକୁ<br/>ଯାଆନ୍ତି।)<br/>Narrator visits a<br/>vegetarian restaurant.\"]\nA --> I2[\"(ସେହି ସମୟ ମଧ୍ୟାହ୍ନ ଭୋଜନ ସମୟ<br/>ଏବଂ ଅତି ଭିଡ଼ପୂର୍ଣ୍ଣ ଥିଲା।)<br/>It is lunch time<br/>and very crowded.\"]\nA --> I3[\"(କେତେକ ଚେୟାର ଓ ଟେବୁଲକୁ<br/>ଏକ କୋଣକୁ ଠେଲି ଦିଆଯାଇଥିଲା।)<br/>Some chairs and tables<br/>had been pushed into a corner.\"]\nend\n\nINTRO --> MAIN\n\nsubgraph MAIN[ ]\ndirection LR\nM[\"🟢 (ଲେଖକଙ୍କ କାର୍ଯ୍ୟ) Narrator's Actions\"]\nM --> M1[\"(ସେ କୋଣ ଟେବୁଲ<br/>ବାଛିଲେ।)<br/>He chose the<br/>corner table.\"]\nM --> M2[\"(ସେ ବସିଲେ ଏବଂ ଖବରକାଗଜ<br/>ଖୋଲିଲେ।)<br/>He seated himself<br/>and opened a newspaper.\"]\nM --> M3[\"(ସେ ଖବର ଉପରେ<br/>ଆଖି ବୁଲାଇବାକୁ ଲାଗିଲେ।)<br/>He began skimming<br/>through the news.\"]\nend\n\nMAIN --> CONCLUSION\n\nsubgraph CONCLUSION[ ]\ndirection LR\nC[\"🔵 (ମୋଡ଼) Turning Point\"]\nC --> C1[\"(ଏକ ଝିଅ ତାଙ୍କୁ<br/>ଚାହିଁଥିବାର ଦେଖାଗଲା।)<br/>A young girl is seen<br/>looking at him.\"]\nC --> C2[\"(ତାହାର ଆଖି ବଡ଼ ଥିଲା ଏବଂ<br/>ଦୁଃଖୀ ଭାବ ଥିଲା।)<br/>Her eyes are large<br/>with a sad expression.\"]\nC --> C3[\"(ଏହା କାହାଣୀର ରହସ୍ୟକୁ<br/>ଆରମ୍ଭ କରେ।)<br/>This sets up the<br/>story's mystery.\"]\nend\n\nlinkStyle 0 stroke-width:0px;\nlinkStyle 4 stroke-width:0px;\nlinkStyle 8 stroke-width:0px;\n\nclassDef title fill:#FFE082,stroke:#FF6F00,stroke-width:3px,color:#000,font-weight:bold;\nclassDef intro fill:#BBDEFB,stroke:#1E88E5,stroke-width:2px,font-weight:bold;\nclassDef body fill:#C8E6C9,stroke:#2E7D32,stroke-width:2px,font-weight:bold;\nclassDef conclusion fill:#F8BBD0,stroke:#C2185B,stroke-width:2px,font-weight:bold;\n\nclass TITLE title;\nclass A,I1,I2,I3 intro;\nclass M,M1,M2,M3 body;\nclass C,C1,C2,C3 conclusion;`,

    `%%{init: {'theme':'base','themeVariables':{'fontSize':'18px'}}}%%\nflowchart TD\n\nTITLE[\"📖 GRAPH-3:<br/>(ଭାଗ-I — ରହସ୍ୟମୟ ଝିଅ)<br/>Part I — The Mysterious Girl\"]\n\nTITLE --> INTRO\n\nsubgraph INTRO[ ]\ndirection LR\nA[\"🟡 (ପ୍ରଶ୍ନ) The Question\"]\nA --> I1[\"(ଯାଉ ଯାଉ, ଝିଅଟି ଧୀର ସ୍ୱରରେ<br/>କ୍ୟାସିୟରକୁ ପଚାରିଲା।)<br/>While leaving, the girl<br/>asks the cashier in a low voice.\"]\nA --> I2[\"(ସେ ପଚାରିଲା: 'ସେହି ଭଦ୍ରଲୋକ<br/>କ'ଣ ଜଣେ ଭାରତୀୟ?')<br/>She asks: 'Is that<br/>gentleman an Indian?'\"]\nA --> I3[\"(କ୍ୟାସିୟର ଉତ୍ତର ଦେଲେ,<br/>'ମୁଁ ଏହା ଭାବୁଛି।')<br/>The cashier replies,<br/>'I think so.'\"]\nend\n\nINTRO --> MAIN\n\nsubgraph MAIN[ ]\ndirection LR\nM[\"🟢 (ତାହାର ପ୍ରତିକ୍ରିୟା) Her Reaction\"]\nM --> M1[\"(ଝିଅଟି ଲେଖକଙ୍କୁ<br/>ପୁଣି ଥରେ ଚାହିଁଲା।)<br/>The girl looks at the<br/>narrator once more.\"]\nM --> M2[\"(ତା'ପରେ ସେ ରେଷ୍ଟୁରାଣ୍ଟରୁ<br/>ବାହାରି ଗଲା।)<br/>She then goes out<br/>of the restaurant.\"]\nM --> M3[\"(ତାହାର ଆଚରଣ ଲେଖକଙ୍କୁ<br/>ଆଶ୍ଚର୍ଯ୍ୟାନ୍ୱିତ କରିଥିଲା।)<br/>Her behaviour<br/>surprises the narrator.\"]\nend\n\nMAIN --> CONCLUSION\n\nsubgraph CONCLUSION[ ]\ndirection LR\nC[\"🔵 (ବଢ଼ୁଥିବା ଜିଜ୍ଞାସା) Rising Curiosity\"]\nC --> C1[\"(ଲେଖକ ଭାବିଲେ ମାମଲାଟି<br/>କ'ଣ ଥିଲା।)<br/>The narrator wonders<br/>what the matter was.\"]\nC --> C2[\"(ତାହାର ଆଗ୍ରହ ଲେଖକଙ୍କ ମନରେ<br/>ଜିଜ୍ଞାସା ଜଗାଇଲା।)<br/>Her interest in him<br/>arouses his curiosity.\"]\nC --> C3[\"(ସେ ଓଏଟରକୁ ପଚାରିଲେ ଯେ ସେ<br/>ଝିଅକୁ ଚିହ୍ନନ୍ତି କି ନାହିଁ।)<br/>He asks the waiter if<br/>he knows the girl.\"]\nend\n\nlinkStyle 0 stroke-width:0px;\nlinkStyle 4 stroke-width:0px;\nlinkStyle 8 stroke-width:0px;\n\nclassDef title fill:#FFE082,stroke:#FF6F00,stroke-width:3px,color:#000,font-weight:bold;\nclassDef intro fill:#BBDEFB,stroke:#1E88E5,stroke-width:2px,font-weight:bold;\nclassDef body fill:#C8E6C9,stroke:#2E7D32,stroke-width:2px,font-weight:bold;\nclassDef conclusion fill:#F8BBD0,stroke:#C2185B,stroke-width:2px,font-weight:bold;\n\nclass TITLE title;\nclass A,I1,I2,I3 intro;\nclass M,M1,M2,M3 body;\nclass C,C1,C2,C3 conclusion;`
  ]
      
}  
]
}; 
