mermaid: [
    `%%{init: {'theme':'base','themeVariables':{'fontSize':'18px'}}}%%\nflowchart TD\n\nTITLE[\"📖 GRAPH-1:<br/>ଉପନିବେଶବାଦର ପରିଚୟ<br/>ଓ ପ୍ରଥମ ପର୍ଯ୍ୟାୟ\"]\n\nTITLE --> INTRO\n\nsubgraph INTRO[ ]\ndirection LR\nA[\"🟡 ଅର୍ଥ\"]\nA --> I1[\"ଉପନିବେଶର ଅର୍ଥ<br/>ବିଦେଶସ୍ଥ ଆବାସ।\"]\nA --> I2[\"ମାତୃ ଦେଶର ଲାଭ<br/>ପାଇଁ କାର୍ଯ୍ୟରେ ଲଗାଇବା।\"]\nA --> I3[\"ଏହାକୁ ଉପନିବେଶବାଦ<br/>କୁହାଯାଏ।\"]\nend\n\nINTRO --> MAIN\n\nsubgraph MAIN[ ]\ndirection LR\nM[\"🟢 ମୁଖ୍ୟ ଲକ୍ଷ୍ୟ ଓ ପର୍ଯ୍ୟାୟ\"]\nM --> M1[\"ବାଣିଜ୍ୟ ଉନ୍ନତି ଓ<br/>ଆର୍ଥିକ ସମୃଦ୍ଧି ଲକ୍ଷ୍ୟ।\"]\nM --> M2[\"ସାମ୍ରାଜ୍ୟ ବିସ୍ତାର ଓ<br/>ଧର୍ମ ପ୍ରୟ ମଧ୍ୟ କାରଣ।\"]\nM --> M3[\"ଷୋଡ଼ଶ ଶତାବ୍ଦୀରେ<br/>ପ୍ରଥମେ ଆରମ୍ଭ ହେଲା।\"]\nM --> M4[\"ଅଷ୍ଟାଦଶ ଶତାବ୍ଦୀ ଶେଷ<br/>ପର୍ଯ୍ୟନ୍ତ ପ୍ରଥମ ପର୍ଯ୍ୟାୟ।\"]\nM --> M5[\"ଊନବିଂଶ ଶତାବ୍ଦୀରେ<br/>ପୁନରୁତ୍ଥାନ ହେଲା।\"]\nend\n\nMAIN --> CONCLUSION\n\nsubgraph CONCLUSION[ ]\ndirection LR\nC[\"🔵 ଫଳାଫଳ\"]\nC --> C1[\"ନୂତନ ପର୍ଯ୍ୟାୟକୁ ଔପନିବେଶିକ<br/>ସାମ୍ରାଜ୍ୟବାଦ କୁହାଯାଏ।\"]\nC --> C2[\"୧୯୧୪ର ପ୍ରଥମ ବିଶ୍ବଯୁଦ୍ଧର<br/>ଏହା ଏକ କାରଣ ଥିଲା।\"]\nC --> C3[\"ଭୌଗୋଳିକ, ବ୍ୟବସାୟିକ ଓ<br/>ଶିଳ୍ପ କାରଣ ଏଥିପାଇଁ ଦାୟୀ।\"]\nend\n\nlinkStyle 0 stroke-width:0px;\nlinkStyle 4 stroke-width:0px;\nlinkStyle 10 stroke-width:0px;\n\nclassDef title fill:#FFE082,stroke:#FF6F00,stroke-width:3px,color:#000,font-weight:bold;\nclassDef intro fill:#BBDEFB,stroke:#1E88E5,stroke-width:2px,font-weight:bold;\nclassDef body fill:#C8E6C9,stroke:#2E7D32,stroke-width:2px,font-weight:bold;\nclassDef conclusion fill:#F8BBD0,stroke:#C2185B,stroke-width:2px,font-weight:bold;\n\nclass TITLE title;\nclass A,I1,I2,I3 intro;\nclass M,M1,M2,M3,M4,M5 body;\nclass C,C1,C2,C3 conclusion;`,

    `%%{init: {'theme':'base','themeVariables':{'fontSize':'18px'}}}%%\nflowchart TD\n\nTITLE[\"📖 GRAPH-2:<br/>ଉପନିବେଶବାଦର କାରଣ:<br/>ଭୌଗୋଳିକ ଆବିଷ୍କାର\"]\n\nTITLE --> INTRO\n\nsubgraph INTRO[ ]\ndirection LR\nA[\"🟡 ପୃଷ୍ଠଭୂମି\"]\nA --> I1[\"ପଞ୍ଚଦଶ, ଷୋଡ଼ଶ ଶତାବ୍ଦୀରେ<br/>ଭୌଗୋଳିକ ଆବିଷ୍କାର ହେଲା।\"]\nA --> I2[\"ଅନେକ ନୂତନ ଅଞ୍ଚଳର<br/>ସନ୍ଧାନ ମିଳିଲା।\"]\nA --> I3[\"ଏସିଆ, ଆଫ୍ରିକାକୁ ଜଳପଥ<br/>ଓ ସ୍ଥଳପଥ ଆବିଷ୍କୃତ ହେଲା।\"]\nend\n\nINTRO --> MAIN\n\nsubgraph MAIN[ ]\ndirection LR\nM[\"🟢 ପ୍ରଭାବ\"]\nM --> M1[\"ଦେଶମାନଙ୍କ ମଧ୍ୟରେ ଯାତାୟାତ,<br/>ଯୋଗାଯୋଗ ସହଜ ହେଲା।\"]\nM --> M2[\"ପ୍ରତ୍ୟେକ ଦେଶ ଅନ୍ୟ ଦେଶ<br/>ବିଷୟରେ ଜ୍ଞାନ ଆହରଣ କଲେ।\"]\nM --> M3[\"ଅନୁସନ୍ଧାନକାରୀ ବ୍ୟବସାୟିକ,<br/>ରାଜନୈତିକ ଲାଭ ଉଲ୍ଲେଖ କଲେ।\"]\nM --> M4[\"ନୂତନ ଅଞ୍ଚଳ ଅନୁକୂଳ<br/>ପରିସ୍ଥିତି ଥିଲା।\"]\nend\n\nMAIN --> CONCLUSION\n\nsubgraph CONCLUSION[ ]\ndirection LR\nC[\"🔵 ମନେରଖ\"]\nC --> C1[\"ଭୌଗୋଳିକ ଆବିଷ୍କାର<br/>ଉପନିବେଶ ପାଇଁ ପଥ ଦେଖାଇଲା।\"]\nC --> C2[\"ଏହା ଉପନିବେଶବାଦର<br/>ପ୍ରଥମ ମୁଖ୍ୟ କାରଣ।\"]\nC --> C3[\"ଆବିଷ୍କାରକଙ୍କ ତାଲିକା<br/>ପ୍ରସ୍ତୁତ କରାଯିବ।\"]\nend\n\nlinkStyle 0 stroke-width:0px;\nlinkStyle 4 stroke-width:0px;\nlinkStyle 9 stroke-width:0px;\n\nclassDef title fill:#FFE082,stroke:#FF6F00,stroke-width:3px,color:#000,font-weight:bold;\nclassDef intro fill:#BBDEFB,stroke:#1E88E5,stroke-width:2px,font-weight:bold;\nclassDef body fill:#C8E6C9,stroke:#2E7D32,stroke-width:2px,font-weight:bold;\nclassDef conclusion fill:#F8BBD0,stroke:#C2185B,stroke-width:2px,font-weight:bold;\n\nclass TITLE title;\nclass A,I1,I2,I3 intro;\nclass M,M1,M2,M3,M4 body;\nclass C,C1,C2,C3 conclusion;`,

    `%%{init: {'theme':'base','themeVariables':{'fontSize':'18px'}}}%%\nflowchart TD\n\nTITLE[\"📖 GRAPH-3:<br/>ଉପନିବେଶବାଦର କାରଣ:<br/>ଲାଭଜନକ ବ୍ୟବସାୟ\"]\n\nTITLE --> INTRO\n\nsubgraph INTRO[ ]\ndirection LR\nA[\"🟡 ଏସିଆର ସାମଗ୍ରୀ\"]\nA --> I1[\"ମସଲା, ରେଶମ, ସୁନା,<br/>ମୁକ୍ତା ଉପଲବ୍ଧ ଥିଲା।\"]\nA --> I2[\"ଏହି ସାମଗ୍ରୀ ସଂଗ୍ରହ କରି<br/>ଇଉରୋପରେ ବିକ୍ରୟ ହେଲା।\"]\nA --> I3[\"ବ୍ୟବସାୟୀମାନେ ପ୍ରଚୁର<br/>ଲାଭ କରିଥିଲେ।\"]\nend\n\nINTRO --> MAIN\n\nsubgraph MAIN[ ]\ndirection LR\nM[\"🟢 ଆଫ୍ରିକାର ସାମଗ୍ରୀ ଓ ଦାସ ବ୍ୟବସାୟ\"]\nM --> M1[\"ସୁନା, ହୀରା, ତମ୍ବା,<br/>ହାତୀଦାନ୍ତ ଲାଭଦାୟକ ଥିଲା।\"]\nM --> M2[\"ଦାସ ବ୍ୟବସାୟ ସବୁଠାରୁ<br/>ବେଶୀ ଲାଭଦାୟକ ଥିଲା।\"]\nM --> M3[\"ଆଫ୍ରିକୀୟଙ୍କୁ ଦାସ ଭାବେ<br/>ଆମେରିକାକୁ ରପ୍ତାନୀ କଲେ।\"]\nM --> M4[\"ପର୍ତ୍ତୁଗାଲ, ସ୍ପେନ୍, ହଲାଣ୍ଡ,<br/>ଫ୍ରାନ୍ସ ପ୍ରତିଦ୍ୱନ୍ଦିତାରେ ଲାଗିଲେ।\"]\nend\n\nMAIN --> CONCLUSION\n\nsubgraph CONCLUSION[ ]\ndirection LR\nC[\"🔵 ମନେରଖ\"]\nC --> C1[\"କ୍ରୀତଦାସ ନିଜ ସ୍ଵାଧୀନତା<br/>ବିକ୍ରୟ କରି ଗୋଲାମି କରୁଥିଲେ।\"]\nC --> C2[\"ଲାଭ ଲୋଭ ଉପନିବେଶ<br/>ସ୍ଥାପନରେ ପ୍ରେରଣା ଦେଲା।\"]\nC --> C3[\"ଏହା ଉପନିବେଶବାଦର<br/>ଦ୍ୱିତୀୟ ମୁଖ୍ୟ କାରଣ।\"]\nend\n\nlinkStyle 0 stroke-width:0px;\nlinkStyle 4 stroke-width:0px;\nlinkStyle 9 stroke-width:0px;\n\nclassDef title fill:#FFE082,stroke:#FF6F00,stroke-width:3px,color:#000,font-weight:bold;\nclassDef intro fill:#BBDEFB,stroke:#1E88E5,stroke-width:2px,font-weight:bold;\nclassDef body fill:#C8E6C9,stroke:#2E7D32,stroke-width:2px,font-weight:bold;\nclassDef conclusion fill:#F8BBD0,stroke:#C2185B,stroke-width:2px,font-weight:bold;\n\nclass TITLE title;\nclass A,I1,I2,I3 intro;\nclass M,M1,M2,M3,M4 body;\nclass C,C1,C2,C3 conclusion;`,

    `%%{init: {'theme':'base','themeVariables':{'fontSize':'18px'}}}%%\nflowchart TD\n\nTITLE[\"📖 GRAPH-4:<br/>ଉପନିବେଶବାଦର କାରଣ:<br/>ଶିଳ୍ପ ବିପ୍ଳବ\"]\n\nTITLE --> INTRO\n\nsubgraph INTRO[ ]\ndirection LR\nA[\"🟡 ଶିଳ୍ପ ବିପ୍ଳବ\"]\nA --> I1[\"ଅଷ୍ଟାଦଶ ଶତାବ୍ଦୀରୁ<br/>ନୂତନ ଯନ୍ତ୍ର ଉଦ୍ଭାବନ ହେଲା।\"]\nA --> I2[\"ଏହା ଇଂଲାଣ୍ଡରେ<br/>ଆରମ୍ଭ ହୋଇଥିଲା।\"]\nA --> I3[\"ଅଳ୍ପ ଶ୍ରମରେ ଦ୍ରବ୍ୟ<br/>ଉତ୍ପାଦନ ବଢ଼ିଲା।\"]\nend\n\nINTRO --> MAIN\n\nsubgraph MAIN[ ]\ndirection LR\nM[\"🟢 ପରିଣାମ\"]\nM --> M1[\"ଅଧ‌ିକ ଉତ୍ପାଦିତ ଦ୍ରବ୍ୟ<br/>ପାଇଁ ବଜାର ଆବଶ୍ୟକ ପଡ଼ିଲା।\"]\nM --> M2[\"ଏସିଆ, ଆଫ୍ରିକାରେ ଶିଳ୍ପ<br/>ବିପ୍ଳବ ହୋଇ ନ ଥିଲା।\"]\nM --> M3[\"ବିନା ପ୍ରତିଯୋଗିତାରେ<br/>ବଜାର ସୃଷ୍ଟି ସହଜ ହେଲା।\"]\nM --> M4[\"କୋଇଲା, ଲୁହା, ସୁନା ଭଳି<br/>କଞ୍ଚାମାଲ ସେଠାରେ ମିଳିଲା।\"]\nend\n\nMAIN --> CONCLUSION\n\nsubgraph CONCLUSION[ ]\ndirection LR\nC[\"🔵 ସାରାଂଶ\"]\nC --> C1[\"ବଜାର ଓ କଞ୍ଚାମାଲ<br/>ଉଭୟ ଆବଶ୍ୟକ ଥିଲା।\"]\nC --> C2[\"ଏହା ଉପନିବେଶ ସ୍ଥାପନକୁ<br/>ପ୍ରୋତ୍ସାହିତ କଲା।\"]\nC --> C3[\"ଏହା ଉପନିବେଶବାଦର<br/>ତୃତୀୟ ମୁଖ୍ୟ କାରଣ।\"]\nend\n\nlinkStyle 0 stroke-width:0px;\nlinkStyle 4 stroke-width:0px;\nlinkStyle 9 stroke-width:0px;\n\nclassDef title fill:#FFE082,stroke:#FF6F00,stroke-width:3px,color:#000,font-weight:bold;\nclassDef intro fill:#BBDEFB,stroke:#1E88E5,stroke-width:2px,font-weight:bold;\nclassDef body fill:#C8E6C9,stroke:#2E7D32,stroke-width:2px,font-weight:bold;\nclassDef conclusion fill:#F8BBD0,stroke:#C2185B,stroke-width:2px,font-weight:bold;\n\nclass TITLE title;\nclass A,I1,I2,I3 intro;\nclass M,M1,M2,M3,M4 body;\nclass C,C1,C2,C3 conclusion;`
  ]


    }  
]
};  
