const mermaidGraphs = [
    `%%{init: {'theme':'base','themeVariables':{'fontSize':'18px'}}}%%\nflowchart TD\n\nTITLE["📖 GRAPH-1:<br/>ଆକୃତି ଓ ଜ୍ୟାମିତିର<br/>ପ୍ରାରମ୍ଭିକ ଧାରଣା"]\n\nTITLE --> INTRO\n\nsubgraph INTRO[ ]\ndirection LR\nA["🟡 ପର୍ଯ୍ୟବେକ୍ଷଣ"]\nA --> I1["ପଥର, ଫୁଲ, ଡକ,<br/>ବିନ୍ଦୁ ଆଦିର ଆକୃତି।"]\nA --> I2["ବସ୍ତୁର ଆକୃତିରେ<br/>ସାମ୍ୟ ଓ ପାର୍ଥକ୍ୟ।"]\nA --> I3["ମଣିଷର ମନରେ<br/>କୌତୁହଳ ସୃଷ୍ଟି।"]\nend\n\nINTRO --> MAIN\n\nsubgraph MAIN[ ]\ndirection LR\nM["🟢 ଅଧ୍ୟୟନର ଆରମ୍ଭ"]\nM --> M1["ମଣିଷ ଆକୃତି<br/>ଅଧ୍ୟୟନ କରିବାକୁ<br/>ଆଗ୍ରହୀ ହେଲା।"]\nM --> M2["ପ୍ରକୃତିର ଆକୃତିକୁ<br/>ଠିକ୍ ଭାବେ<br/>ବ୍ୟବହାର କଲା।"]\nend\n\nMAIN --> CONCLUSION\n\nsubgraph CONCLUSION[ ]\ndirection LR\nC["🔵 ଫଳାଫଳ"]\nC --> C1["ମଣିଷର ସୁବିଧା<br/>ବୃଦ୍ଧି ପାଇଲା।"]\nC --> C2["ଜ୍ଞାନର ବିକାଶ<br/>ହେଲା।"]\nend\n\nlinkStyle 0 stroke-width:0px;\nlinkStyle 3 stroke-width:0px;\nlinkStyle 6 stroke-width:0px;\n\nclassDef title fill:#FFE082,stroke:#FF6F00,stroke-width:3px,color:#000,font-weight:bold;\nclassDef intro fill:#BBDEFB,stroke:#1E88E5,stroke-width:2px,font-weight:bold;\nclassDef body fill:#C8E6C9,stroke:#2E7D32,stroke-width:2px,font-weight:bold;\nclassDef conclusion fill:#F8BBD0,stroke:#C2185B,stroke-width:2px,font-weight:bold;\n\nclass TITLE title;\nclass A,I1,I2,I3 intro;\nclass M,M1,M2 body;\nclass C,C1,C2 conclusion;`,

    `%%{init: {'theme':'base','themeVariables':{'fontSize':'18px'}}}%%\nflowchart TD\n\nTITLE["📖 GRAPH-2:<br/>'ଜ୍ୟାମିତି' ଶବ୍ଦର<br/>ଉତ୍ପତ୍ତି ଓ ଅର୍ଥ"]\n\nTITLE --> INTRO\n\nsubgraph INTRO[ ]\ndirection LR\nA["🟡 ଆବଶ୍ୟକତା"]\nA --> I1["ଆକୃତିକୁ ମାପିବାର<br/>ଆବଶ୍ୟକତାରୁ<br/>ଜ୍ୟାମିତି ଆରମ୍ଭ।"]\nend\n\nINTRO --> MAIN\n\nsubgraph MAIN[ ]\ndirection LR\nM["🟢 ଶବ୍ଦ ବ୍ୟୁତ୍ପତ୍ତି"]\nM --> M1["ସଂସ୍କୃତରେ 'ଜ୍ୟା'<br/>ଅର୍ଥ ପୃଥିବୀ।"]\nM --> M2["ସଂସ୍କୃତରେ 'ମିତି'<br/>ଅର୍ଥ ମାପ।"]\nM --> M3["Geo (ପୃଥିବୀ) ଓ<br/>Metron (ମାପ)<br/>ଗ୍ରୀକ୍ ଶବ୍ଦ।"]\nend\n\nMAIN --> CONCLUSION\n\nsubgraph CONCLUSION[ ]\ndirection LR\nC["🔵 ମନେରଖ"]\nC --> C1["ଜମି ମାପିବାର<br/>ଆବଶ୍ୟକତାରୁ<br/>ଜ୍ୟାମିତିର ବିକାଶ।"]\nend\n\nlinkStyle 0 stroke-width:0px;\nlinkStyle 2 stroke-width:0px;\nlinkStyle 6 stroke-width:0px;\n\nclassDef title fill:#FFE082,stroke:#FF6F00,stroke-width:3px,color:#000,font-weight:bold;\nclassDef intro fill:#BBDEFB,stroke:#1E88E5,stroke-width:2px,font-weight:bold;\nclassDef body fill:#C8E6C9,stroke:#2E7D32,stroke-width:2px,font-weight:bold;\nclassDef conclusion fill:#F8BBD0,stroke:#C2185B,stroke-width:2px,font-weight:bold;\n\nclass TITLE title;\nclass A,I1 intro;\nclass M,M1,M2,M3 body;\nclass C,C1 conclusion;`,

    `%%{init: {'theme':'base','themeVariables':{'fontSize':'18px'}}}%%\nflowchart TD\n\nTITLE["📖 GRAPH-3:<br/>ପ୍ରାଚୀନ ସଭ୍ୟତାରେ<br/>ଜ୍ୟାମିତିର ବିକାଶ"]\n\nTITLE --> INTRO\n\nsubgraph INTRO[ ]\ndirection LR\nA["🟡 ମିଶର ସଭ୍ୟତା"]\nA --> I1["ମିଶରରେ ପ୍ରଥମ<br/>ଜ୍ୟାମିତିର ବିକାଶ।"]\nA --> I2["ନୀଳନଦୀର ବନ୍ୟା<br/>ପରେ ଜମି ବାଣ୍ଟିବା।"]\nend\n\nINTRO --> MAIN\n\nsubgraph MAIN[ ]\ndirection LR\nM["🟢 ଭାରତୀୟ ଜ୍ୟାମିତି"]\nM --> M1["ବୈଦିକ ଋଷିମାନେ<br/>ଯଜ୍ଞବେଦୀ ତିଆରି<br/>କରୁଥିଲେ।"]\nM --> M2["'ଶୁଳ୍ବ ସୂତ୍ର'<br/>(ଖ୍ରୀ.ପୂ. ୮୦୦-୫୦୦)<br/>ଏକ ଜ୍ୟାମିତି ଶାସ୍ତ୍ର।"]\nM --> M3["ମହେଞ୍ଜୋଦାରୋ ଓ<br/>ହରପ୍ପା ନଗର<br/>ଯୋଜନା।"]\nend\n\nMAIN --> CONCLUSION\n\nsubgraph CONCLUSION[ ]\ndirection LR\nC["🔵 ପରବର୍ତ୍ତୀ ଅବଦାନ"]\nC --> C1["ଆସିରିଆ, ଆର୍ଯ୍ୟଭଟ,<br/>ବ୍ରହ୍ମଗୁପ୍ତ, ମହାବୀର<br/>ଅବଦାନ ଦେଲେ।"]\nend\n\nlinkStyle 0 stroke-width:0px;\nlinkStyle 3 stroke-width:0px;\nlinkStyle 7 stroke-width:0px;\n\nclassDef title fill:#FFE082,stroke:#FF6F00,stroke-width:3px,color:#000,font-weight:bold;\nclassDef intro fill:#BBDEFB,stroke:#1E88E5,stroke-width:2px,font-weight:bold;\nclassDef body fill:#C8E6C9,stroke:#2E7D32,stroke-width:2px,font-weight:bold;\nclassDef conclusion fill:#F8BBD0,stroke:#C2185B,stroke-width:2px,font-weight:bold;\n\nclass TITLE title;\nclass A,I1,I2 intro;\nclass M,M1,M2,M3 body;\nclass C,C1 conclusion;`,

    `%%{init: {'theme':'base','themeVariables':{'fontSize':'18px'}}}%%\nflowchart TD\n\nTITLE["📖 GRAPH-4:<br/>ପ୍ରାୟୋଗିକ<br/>(Practical) ଜ୍ୟାମିତି"]\n\nTITLE --> INTRO\n\nsubgraph INTRO[ ]\ndirection LR\nA["🟡 ପ୍ରାରମ୍ଭିକ ଅବସ୍ଥା"]\nA --> I1["ପରୀକ୍ଷା ଓ ଅନୁଭବ<br/>ଉପରେ ଆଧାରିତ<br/>ଜ୍ୟାମିତି।"]\nend\n\nINTRO --> MAIN\n\nsubgraph MAIN[ ]\ndirection LR\nM["🟢 ପଦ୍ଧତି"]\nM --> M1["ପ୍ରତ୍ୟକ୍ଷ ପର୍ଯ୍ୟବେକ୍ଷଣ<br/>କରି ସୂତ୍ର<br/>ତିଆରି ହେଲା।"]\nM --> M2["ଜ୍ୟାମିତି ଅଭିଜ୍ଞତା<br/>ଉପରେ ଆଧାରିତ<br/>ଥିଲା।"]\nend\n\nMAIN --> CONCLUSION\n\nsubgraph CONCLUSION[ ]\ndirection LR\nC["🔵 ମନେରଖ"]\nC --> C1["ଏହା ତାର୍କିକ<br/>ପ୍ରମାଣ ଉପରେ<br/>ଆଧାରିତ ନଥିଲା।"]\nend\n\nlinkStyle 0 stroke-width:0px;\nlinkStyle 2 stroke-width:0px;\nlinkStyle 5 stroke-width:0px;\n\nclassDef title fill:#FFE082,stroke:#FF6F00,stroke-width:3px,color:#000,font-weight:bold;\nclassDef intro fill:#BBDEFB,stroke:#1E88E5,stroke-width:2px,font-weight:bold;\nclassDef body fill:#C8E6C9,stroke:#2E7D32,stroke-width:2px,font-weight:bold;\nclassDef conclusion fill:#F8BBD0,stroke:#C2185B,stroke-width:2px,font-weight:bold;\n\nclass TITLE title;\nclass A,I1 intro;\nclass M,M1,M2 body;\nclass C,C1 conclusion;`

   ];
