const mermaidGraphs = [
    `%%{init: {'theme':'base','themeVariables':{'fontSize':'18px'}}}%%\nflowchart TD\n\nTITLE[\"📖 GRAPH-1:<br/>ସିଂହ ଓ ଶଶକ<br/>କାହାଣୀର ଆରମ୍ଭ\"]\n\nTITLE --> INTRO\n\nsubgraph INTRO[ ]\ndirection LR\nA[\"🟡 ପରିଚୟ\"]\nA --> I1[\"ଭାସୁରକ ନାମକ ଏକ ସିଂହ<br/>ବଣରେ ରହୁଥିଲା।\"]\nA --> I2[\"ସେ ପ୍ରତିଦିନ ଅନେକ<br/>ପଶୁ ମାରୁଥିଲା।\"]\nA --> I3[\"ପଶୁମାନେ ଏଥିରେ<br/>ବ୍ୟଥିତ ହେଲେ।\"]\nend\n\nINTRO --> MAIN\n\nsubgraph MAIN[ ]\ndirection LR\nM[\"🟢 ପଶୁମାନଙ୍କର ପ୍ରସ୍ତାବ\"]\nM --> M1[\"ପଶୁମାନେ ମିଶି<br/>ସିଂହ ପାଖକୁ ଗଲେ।\"]\nM --> M2[\"ପ୍ରତିଦିନ ଏକ ପଶୁ<br/>ପଠାଇବାକୁ କହିଲେ।\"]\nM --> M3[\"ସିଂହ ଏହି<br/>ପ୍ରସ୍ତାବ ମାନିଲା।\"]\nM --> M4[\"ସିଂହ ଏକ<br/>ଚେତାବନୀ ଦେଲା।\"]\nM --> M5[\"ପଶୁ ନ ଆସିଲେ ସେ<br/>ସମସ୍ତଙ୍କୁ ମାରିବ।\"]\nend\n\nMAIN --> CONCLUSION\n\nsubgraph CONCLUSION[ ]\ndirection LR\nC[\"🔵 ପାଳି ବ୍ୟବସ୍ଥା\"]\nC --> C1[\"ପ୍ରତିଦିନ ଏକ ପଶୁ<br/>ପାଳି କ୍ରମେ ଯାଉଥିଲା।\"]\nC --> C2[\"ଏକଦିନ ଶଶକର<br/>ପାଳି ଆସିଲା।\"]\nC --> C3[\"ଶଶକ ବିଳମ୍ବରେ ଗଲା,<br/>ଉପାୟ ଚିନ୍ତା କଲା।\"]\nend\n\nlinkStyle 0 stroke-width:0px;\nlinkStyle 4 stroke-width:0px;\nlinkStyle 10 stroke-width:0px;\n\nclassDef title fill:#FFE082,stroke:#FF6F00,stroke-width:3px,color:#000,font-weight:bold;\nclassDef intro fill:#BBDEFB,stroke:#1E88E5,stroke-width:2px,font-weight:bold;\nclassDef body fill:#C8E6C9,stroke:#2E7D32,stroke-width:2px,font-weight:bold;\nclassDef conclusion fill:#F8BBD0,stroke:#C2185B,stroke-width:2px,font-weight:bold;\n\nclass TITLE title;\nclass A,I1,I2,I3 intro;\nclass M,M1,M2,M3,M4,M5 body;\nclass C,C1,C2,C3 conclusion;`,

    `%%{init: {'theme':'base','themeVariables':{'fontSize':'18px'}}}%%\nflowchart TD\n\nTITLE[\"📖 GRAPH-2:<br/>ଶଶକର ବୁଦ୍ଧି<br/>ଓ କୂଅର ଯୋଜନା\"]\n\nTITLE --> INTRO\n\nsubgraph INTRO[ ]\ndirection LR\nA[\"🟡 କୂଅ ଦର୍ଶନ\"]\nA --> I1[\"ଶଶକ ବାଟରେ<br/>ଏକ କୂଅ ଦେଖିଲା।\"]\nA --> I2[\"କୂଅରେ ନିଜର<br/>ପ୍ରତିବିମ୍ବ ଦେଖିଲା।\"]\nA --> I3[\"ଏଥିରୁ ଏକ<br/>ଉପାୟ ଭାବିଲା।\"]\nend\n\nINTRO --> MAIN\n\nsubgraph MAIN[ ]\ndirection LR\nM[\"🟢 ସିଂହ ପାଖକୁ ଯାତ୍ରା\"]\nM --> M1[\"ଶଶକ ବିଳମ୍ବରେ<br/>ସିଂହ ପାଖରେ ପହଞ୍ଚିଲା।\"]\nM --> M2[\"ସିଂହ କ୍ରୋଧିତ ହୋଇ<br/>ଧମକ ଦେଲା।\"]\nM --> M3[\"ଶଶକ କ୍ଷମା ମାଗି<br/>କାରଣ କହିଲା।\"]\nM --> M4[\"ଏକ ଅନ୍ୟ ସିଂହ ବାଟରେ<br/>ରୋକିଥିଲା ବୋଲି କହିଲା।\"]\nM --> M5[\"ସେ ସିଂହ ନିଜକୁ<br/>ରାଜା କହୁଥିଲା ବୋଲି କହିଲା।\"]\nend\n\nMAIN --> CONCLUSION\n\nsubgraph CONCLUSION[ ]\ndirection LR\nC[\"🔵 ସିଂହର କ୍ରୋଧ\"]\nC --> C1[\"ଭାସୁରକ ଶତ୍ରୁ ସିଂହକୁ<br/>ଦେଖିବାକୁ ଚାହିଁଲା।\"]\nC --> C2[\"ଶଶକ ତାକୁ କୂଅ<br/>ପାଖକୁ ନେଇଗଲା।\"]\nC --> C3[\"ଏହା ଥିଲା ଶଶକର<br/>ଚତୁର ଯୋଜନା।\"]\nend\n\nlinkStyle 0 stroke-width:0px;\nlinkStyle 4 stroke-width:0px;\nlinkStyle 10 stroke-width:0px;\n\nclassDef title fill:#FFE082,stroke:#FF6F00,stroke-width:3px,color:#000,font-weight:bold;\nclassDef intro fill:#BBDEFB,stroke:#1E88E5,stroke-width:2px,font-weight:bold;\nclassDef body fill:#C8E6C9,stroke:#2E7D32,stroke-width:2px,font-weight:bold;\nclassDef conclusion fill:#F8BBD0,stroke:#C2185B,stroke-width:2px,font-weight:bold;\n\nclass TITLE title;\nclass A,I1,I2,I3 intro;\nclass M,M1,M2,M3,M4,M5 body;\nclass C,C1,C2,C3 conclusion;`,

    `%%{init: {'theme':'base','themeVariables':{'fontSize':'18px'}}}%%\nflowchart TD\n\nTITLE[\"📖 GRAPH-3:<br/>ସିଂହର ବିନାଶ<br/>ଓ କାହାଣୀର ଶିକ୍ଷା\"]\n\nTITLE --> INTRO\n\nsubgraph INTRO[ ]\ndirection LR\nA[\"🟡 କୂଅ ପାଖରେ\"]\nA --> I1[\"ସିଂହ କୂଅ ମଧ୍ୟରେ<br/>ନିଜ ପ୍ରତିବିମ୍ବ ଦେଖିଲା।\"]\nA --> I2[\"ସେ ଏହାକୁ ଶତ୍ରୁ<br/>ବୋଲି ଭାବିଲା।\"]\nA --> I3[\"ସେ ଜୋର୍ରେ<br/>ଗର୍ଜନ କଲା।\"]\nend\n\nINTRO --> MAIN\n\nsubgraph MAIN[ ]\ndirection LR\nM[\"🟢 ପ୍ରତିଧ୍ୱନି ଓ ମୃତ୍ୟୁ\"]\nM --> M1[\"କୂଅରୁ ଏକ<br/>ପ୍ରତିଧ୍ୱନି ଆସିଲା।\"]\nM --> M2[\"ସିଂହ ଏହାକୁ ଶତ୍ରୁର<br/>ଗର୍ଜନ ମନେକଲା।\"]\nM --> M3[\"ଅତି କ୍ରୋଧରେ ସେ<br/>କୂଅରେ ଡେଇଁ ପଡ଼ିଲା।\"]\nM --> M4[\"ସିଂହ କୂଅରେ ପଡ଼ି<br/>ମୃତ୍ୟୁବରଣ କଲା।\"]\nM --> M5[\"ବୁଦ୍ଧିବଳ ଶକ୍ତିଠାରୁ<br/>ବଡ଼ ବୋଲି ପ୍ରମାଣିତ ହେଲା।\"]\nend\n\nMAIN --> CONCLUSION\n\nsubgraph CONCLUSION[ ]\ndirection LR\nC[\"🔵 ଶିକ୍ଷା\"]\nC --> C1[\"ଶଶକ ଓ ସବୁ ପଶୁ<br/>ଆନନ୍ଦିତ ହେଲେ।\"]\nC --> C2[\"ସେମାନେ ବଣରେ<br/>ସୁଖରେ ରହିଲେ।\"]\nC --> C3[\"ବୁଦ୍ଧି ବଳରେ ଅତ୍ୟାଚାରୀର<br/>ବିନାଶ ସମ୍ଭବ।\"]\nend\n\nlinkStyle 0 stroke-width:0px;\nlinkStyle 4 stroke-width:0px;\nlinkStyle 10 stroke-width:0px;\n\nclassDef title fill:#FFE082,stroke:#FF6F00,stroke-width:3px,color:#000,font-weight:bold;\nclassDef intro fill:#BBDEFB,stroke:#1E88E5,stroke-width:2px,font-weight:bold;\nclassDef body fill:#C8E6C9,stroke:#2E7D32,stroke-width:2px,font-weight:bold;\nclassDef conclusion fill:#F8BBD0,stroke:#C2185B,stroke-width:2px,font-weight:bold;\n\nclass TITLE title;\nclass A,I1,I2,I3 intro;\nclass M,M1,M2,M3,M4,M5 body;\nclass C,C1,C2,C3 conclusion;`
  ];
  
      

